export const QUERY_KEYS = {
  PROFILE: 'PROFILE',
  USERS: 'USERS',
  COMPANIES: 'COMPANIES',
  JOBS: 'JOBS',
  JOBS_DETAIL: 'JOBS_DETAIL',
  COMPANY_DETAIL: 'COMPANY_DETAIL',
  RESUME_BY_USER: 'RESUME_BY_USER',
  SUBSCRIBER_SKILLS: 'SUBSCRIBER_SKILLS',
} as const;
